critical:
  - '/(\s|^)(critical|urgent)(:|\s|$)/i'

enhancement:
  - '/(\s|^)(feat|features|request|new|improve|create|build|enhancement|reworks?)(:|\s|$)/i'

bug:
  - '/(\s|^)(bug|fix|fixes|issue|solve|correct|defect)(:|\s|$)/i'

documentation:
  - '/(\s|^)(docs|document|documentation|readme)(:|\s|$)/i'

invalid:
  - '/(\s|^)(invalid)(:|\s|$)/i'

help wanted:
  - '/(\s|^)(help|need|info)(:|\s|$)/i'

fastled helper:
  - '/(\s|^)(svitlobot)(:|\s|$)/i'

misic leds:
  - '/(\s|^)(healthcheck)(:|\s|$)/i'

nerdminer:
  - '/(\s|^)(custom(-|\s|_)url)(:|\s|$)/i'

shadow:
  - '/(\s|^)(all-in-one|aio)(:|\s|$)/i'
