substitutions:
  name: "esp-nerdminer"
  friendly_name: "Music Led Component"
  project_name: "ajs.Light - Music Led - Sound Reactive"
  project_version: "1.5.5"
  comment: "ESPHome Music Led"
  pin_leds: "GPIO16"
  num_leds: "100"
  type_leds: "BGR"
  color_correct_bright: "50%"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  comment: $comment
  build_path: ./.build/$name
  project:
    name: "${project_name}"
    version: "${project_version}"

dashboard_import:
  package_import_url: github://andrewjswan/esphome-components/examples/music_leds.yaml@main

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

logger:
  level: INFO

mdns:
  disabled: false

web_server:
  port: 80
  log: false
  version: 3

wifi:
  ap: {}

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/andrewjswan/esphome-components
      ref: main
    components: [fastled_helper, music_leds]
    refresh: 60s

fastled_helper:
  music_leds: true

i2s_audio:
  i2s_lrclk_pin: GPIO15
  i2s_bclk_pin: GPIO14

microphone:
  - platform: i2s_audio
    id: adc_mic
    adc_type: external
    sample_rate: 10240
    # bits_per_sample: 16bit
    bits_per_sample: 32bit
    i2s_din_pin: GPIO32
    channel: right
    pdm: false

music_leds:
  id: music_light
  mic_id: adc_mic

light:
  # Neopixel with Music Leds / Sound Reactive
  - platform: neopixelbus
    id: neopixel_led
    type: ${type_leds}
    pin: ${pin_leds}
    num_leds: ${num_leds}
    name: ${name} NeoPixel
    icon: mdi:string-lights
    color_correct: [$color_correct_bright, $color_correct_bright, $color_correct_bright]
    variant: 800KBPS  # WS2812 (same as 800KBPS)
    effects:
      - music_leds_effect:
          name: Binmap with Music
          mode: BINMAP
      - music_leds_effect:
          name: Grav with Music
          mode: GRAV
      - music_leds_effect:
          name: Gravicenter with Music
          mode: GRAVICENTER
      - music_leds_effect:
          name: Gravicentric with Music
          mode: GRAVICENTRIC
      - music_leds_effect:
          name: Pixels with Music
          mode: PIXELS
      - music_leds_effect:
          name: Jungles with Music
          mode: JUNGLES
      - music_leds_effect:
          name: Midnoise with Music
          mode: MIDNOISE
