substitutions:
  name: "esp-nerdminer"
  friendly_name: "NerdMiner Component"
  project_name: "ajs.component-nedrminer"
  project_version: "1.5.0"
  comment: "ESPHome NerdMiner"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  comment: $comment
  build_path: ./.build/$name
  project:
    name: "${project_name}"
    version: "${project_version}"

dashboard_import:
  package_import_url: github://andrewjswan/esphome-components/examples/nerdminer.yaml@main

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
    on_begin:
      then:
        - lambda: |-
            id(esp_miner)->stop();

logger:
  level: INFO

mdns:
  disabled: false

web_server:
  port: 80
  log: false
  version: 3

wifi:
  ap: {}

captive_portal:

external_components:
  - source:
      type: local
      path: ../components
    components: [nerdminer]

nerdminer:
  id: esp_miner
  walletid: "wallet"

binary_sensor:
  - platform: template
    name: "${friendly_name} State"
    id: miner_state
    icon: mdi:lan-connect
    lambda: |-
      return id(esp_miner).getMinerState();
    web_server:
      sorting_weight: 1

sensor:
  - platform: template
    name: "${friendly_name} Valid Blocks"
    icon: mdi:trophy-award
    lambda: |-
      return id(esp_miner).getValidBlocks();
    accuracy_decimals: 0
    update_interval: 60s
    web_server:
      sorting_weight: 2

  - platform: template
    name: "${friendly_name} Block Templates"
    icon: mdi:code-block-brackets
    lambda: |-
      return id(esp_miner).getBlockTemplates();
    accuracy_decimals: 0
    update_interval: 60s
    web_server:
      sorting_weight: 3

  - platform: template
    name: "${friendly_name} Best Difficulty"
    icon: mdi:vector-difference
    lambda: |-
      return id(esp_miner).getBestDiff();
    accuracy_decimals: 3
    update_interval: 60s
    web_server:
      sorting_weight: 4

  - platform: template
    name: "${friendly_name} 32Bit Shares"
    icon: mdi:cpu-32-bit
    lambda: |-
      return id(esp_miner).get32BitShares();
    accuracy_decimals: 0
    update_interval: 60s
    web_server:
      sorting_weight: 5

  - platform: template
    name: "${friendly_name} Speed"
    icon: mdi:speedometer
    lambda: |-
      return id(esp_miner).getHashrate();
    accuracy_decimals: 2
    unit_of_measurement: "KH/s"
    update_interval: 60s
    web_server:
      sorting_weight: 6

  - platform: template
    name: "${friendly_name} Hashes"
    icon: mdi:pound-box-outline
    lambda: |-
      return id(esp_miner).getTotalHashes();
    accuracy_decimals: 0
    unit_of_measurement: "MH"
    update_interval: 60s
    web_server:
      sorting_weight: 7

  - platform: internal_temperature
    name: ${friendly_name} Device Temperature
    id: device_temperature
    icon: mdi:thermometer
    device_class: temperature
    entity_category: diagnostic

  - platform: uptime
    name: "${friendly_name} Uptime"
    entity_category: diagnostic

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    entity_category: diagnostic
    icon: mdi:signal

button:
  - platform: restart
    name: "${friendly_name} Restart"
    id: Restart
    entity_category: diagnostic
    icon: mdi:restart

  - platform: factory_reset
    name: "${friendly_name} Restart with Factory Default Settings"
    id: Reset
    entity_category: diagnostic
    disabled_by_default: true

text_sensor:
  - platform: version
    name: ${friendly_name} ESPHome Version
    hide_timestamp: true
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:ip
    ssid:
      name: "${friendly_name} Connected SSID"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:access-point-network
    mac_address:
      name: "${friendly_name} Mac Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:console-network
