substitutions:
  device: "esp_shadow"
  name: "shadow"
  friendly_name: "Shadow Component"
  project_name: "ajs.component-shadow"
  project_version: "1.5.0"
  comment: "ESPHome Shadow"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  comment: $comment
  build_path: ./.build/$device
  project:
    name: "${project_name}"
    version: "${project_version}"

dashboard_import:
  package_import_url: github://andrewjswan/esphome-components/examples/shadow.yaml@main

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
    on_begin:
      then:
        - lambda: |-
            id(esp_shadow)->stop();
  - platform: web_server
    on_begin:
      then:
        - lambda: |-
            id(esp_shadow)->stop();

logger:
  level: INFO

mdns:
  disabled: false

web_server:
  port: 80
  log: false
  version: 3

wifi:
  ap: {}

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/andrewjswan/esphome-components
      ref: main
    components: [shadow]
    refresh: 60s

script:
  - id: some_script
    then:
      - logger.log: "${friendly_name} Script Running..."
    mode: queued

shadow:
  id: esp_shadow
  script_id: some_script
  interval: 60

sensor:
  - platform: uptime
    name: "Uptime"
    entity_category: diagnostic

  - platform: wifi_signal
    name: "WiFi Signal"
    entity_category: diagnostic
    icon: mdi:signal

button:
  - platform: restart
    name: "Restart"
    id: Restart
    entity_category: diagnostic
    icon: mdi:restart

  - platform: factory_reset
    name: "Restart with Factory Default Settings"
    id: Reset
    entity_category: diagnostic
    disabled_by_default: true

text_sensor:
  - platform: version
    name: ESPHome Version
    hide_timestamp: true
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      name: "IP Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:ip
    ssid:
      name: "Connected SSID"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:access-point-network
    mac_address:
      name: "Mac Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:console-network
