"""Constants for Music Leds component for ESPHome."""

CONF_BAND_PASS_FILTER = "band_pass_filter"
CONF_FFT_SCALING = "fft_scaling_mode"
CONF_GAINCONTROL = "gain_control"
CONF_MUSIC_LEDS_ID = "music_leds_id"
CONF_SOUND_DYNAMICS_LIMITER = "sound_dynamics_limiter"
CONF_SR_GAIN = "sample_gain"
CONF_SR_SQUELCH = "squelch value"
CONF_TASK_CORE = "task_core"
CONF_TASK_PRIORITY = "task_priority"
