"""Constants for Music Leds component for ESPHome."""

BIT_16 = 16
BIT_32 = 32

CONF_MIC_ID = "mic_id"
CONF_MUSIC_LEDS_ID = "music_leds_id"

MODE_BINMAP = "BINMAP"
MODE_GRAV = "GRAV"
MODE_GRAVICENTER = "GRAVICENTER"
MODE_GRAVICENTRIC = "GRAVICENTRIC"
MODE_PIXELS = "PIXELS"
MODE_JUNGLES = "JUNGLES"
MODE_MIDNOISE = "MIDNOISE"

MUSIC_LEDS_EFFECTS = [
    MODE_BINMAP,
    MODE_GRAV,
    MODE_GRAVICENTER,
    MODE_GRAVICENTRIC,
    MODE_PIXELS,
    MODE_JUNGLES,
    MODE_MIDNOISE,
]
